### ISSUE TITLE
修改掉落方案

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/DeathChest#2]
添加配置：

* 是否保留护甲物品栏
* 是否保留快捷栏
* 重生后给一个可选 buff

当以上选项都为 `true` 时，玩家死亡后护甲、副手、快捷栏的物品不会掉落丢失，背包中的物品被保存在死亡箱子内。护甲保留在对应护甲位，其余物品在玩家背包内（不要放在快捷栏，以免眼瘸玩家认为自己没丢东西）

重生 buff 的配置

```
respawn_effect:
- speed:2:1200 # 1200 tick 速度 3
- resistance:1:1200
- weakness:1:1200
```

**Comment by ReinWD** [comment]
> ```
> respawn_effect:
> - speed:2:1200 # 1200 tick 速度 3
> - resistance:1:1200
> - weakness:1:1200
> ```

此处命名需要使用Spigot API中[PotionEffectType](https://hub.spigotmc.org/javadocs/spigot/index.html?org/bukkit/potion/PotionEffectType.html)类定义的enum，大小写任意。
其余需求已实现
